#
# Production services configuration for Soundstorm. Adds the `redis` and
# `sidekiq` services for background job processing and cache storage,
# and tags the `web` image to that of its production variant. This also
# builds the production image with a hard-coded RAILS_ENV=production to
# ensure the image builds with assets correctly.
#
version: '3'
services:
  redis:
    image: redis
    volumes:
      - redis:/data
  web:
    build:
      context: .
      args:
        - RAILS_ENV=production
        - SECRET_KEY_BASE
    image: weathermen/soundstorm
    env_file:
      - config/production.env
    secrets:
      - master_key
  sidekiq:
    image: weathermen/soundstorm
    command: bundle exec sidekiq -C config/sidekiq.yml
    env_file:
      - config/production.env
    secrets:
      - master_key
volumes:
  redis:
secrets:
  master_key:
    file: ./config/master.key
