#
# Production services configuration for Soundstorm. Adds the `redis` and
# `sidekiq` services for background job processing and cache storage,
# and tags the `web` image to that of its production variant. This also
# builds the production image with a hard-coded RAILS_ENV=production to
# ensure the image builds with assets correctly.
#
version: '3.7'
services:
  redis:
    image: redis
    volumes:
      - redis:/data
  web:
    image: weathermen/soundstorm
    build:
      context: .
      args:
        - RAILS_ENV=production
        - RAILS_MASTER_KEY
    image: weathermen/soundstorm
    secrets:
      - master
  sidekiq:
    image: weathermen/soundstorm
    command: bundle exec sidekiq -C config/sidekiq.yml
    secrets:
      - master
volumes:
  redis:
secrets:
  master:
    file: ./config/master.key
  credentials:
    file: ./config/credentials.yml.enc
