#
# Production services configuration for Soundstorm. Adds the `redis` and
# `sidekiq` services, and disables `mailcatcher`. All services in
# production are created using released images from the registry, which
# have been ostensibly verified as working.

version: '3'
services:
  web:
    image: weathermen/soundstorm
    environment:
      - SOUNDSTORM_HOST
      - SOUNDSTORM_CDN_URL
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_REGION
      - AWS_S3_BUCKET_NAME
      - RAILS_SERVE_STATIC_FILES=false
      - RAILS_LOG_TO_STDOUT=true
      - SMTP_HOST
      - SMTP_PORT
      - SMTP_USERNAME
      - SMTP_PASSWORD
      - SMTP_AUTH
      - SMTP_TLS
