name: Tests
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
    steps:
      - uses: actions/checkout@v1
      - name: Build Application
        run: make install
      - name: Run Tests
        run: make ci
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.codeclimate_id }}
      - name: Clean Up All Artifacts
        run: make clean
