name: CI
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build Application
        run: make install
        env:
          RAILS_ENV: test
      - name: Run Tests
        run: make ci
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.codeclimate_id }}
          RAILS_ENV: test
