name: Build
on:
  push:
    branches: [master]
jobs:
  build:
    name: Build and Deploy Latest Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v1
      - name: Create GitHub Deployment
        run: |
          curl https://api.github.com/repos/${{ github.repository }}/deployments \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/json; charset=utf-8" \
            -d "{\"ref\": \"${{ github.ref }}\", \"description\": \"Continuous Deployment via GitHub Actions\" }"
      - name: Set Initial GitHub Deployment Status
          uses: unacast/actions-github-deployment-status@master
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            status: pending
      - name: Build and Publish Image
        uses: elgohr/Publish-Docker-Github-Action@master
        env:
          RAILS_ENV: production
          RAILS_MASTER_KEY: ${{ secrets.master_key }}
        with:
          name: weathermen/soundstorm
          username: ${{ secrets.docker_login }}
          password: ${{ secrets.docker_password }}
          tag_names: true
          build_args: 'RAILS_ENV,RAILS_MASTER_KEY'
      - name: Configure Kubernetes with DigitalOcean
        uses: digitalocean/action-doctl@master
        env:
          DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.digitalocean_token }}
        with:
          args: kubernetes cluster kubeconfig save soundstorm
      - name: Deploy to Kubernetes Cluster
        run: make deploy
      - name: Notify Sentry of Deployment
        uses: juankaram/sentry-release@master
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.sentry_token }}
          SENTRY_ORG: soundstorm-social
          SENTRY_PROJECT: soundstorm
          ENVIRONMENT: production
      - name: Update GitHub Deployment
          if: always()
          uses: unacast/actions-github-deployment-status@master
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            status: ${{ job.status }}
