name: Build
on:
  push:
    branches: [master]
jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v1
      - name: Build and Publish Image
        uses: elgohr/Publish-Docker-Github-Action@master
        env:
          RAILS_ENV: production
          SECRET_KEY_BASE: ${{ secrets.key_base }}
        with:
          name: weathermen/soundstorm
          username: ${{ secrets.docker_login }}
          password: ${{ secrets.docker_password }}
          tag_names: true
          build_args: 'RAILS_ENV,RAILS_MASTER_KEY'
      # - name: Configure Kubernetes with DigitalOcean
      #   uses: digitalocean/action-doctl@master
      #   env:
      #     DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.digitalocean_token }}
      #   with:
      #     args: kubernetes cluster kubeconfig save soundstorm
      # - name: Deploy to Kubernetes Cluster
      #   run: make deploy
